import Head from "next/head"
import { Navbar } from "../ui";
import { useContext } from "react";
import { ThemeContext } from "../../context/ui/themeContext";
import { Open_Sans } from "@next/font/google";

const openSans = Open_Sans({ subsets: ["latin"] });

export const MainLayout = ({children, title = "Portafolio"}) => {
    
    const {checked} = useContext(ThemeContext)

    const theme = { light: "winter", dark: "night"};
    
  return (
    <>
        <Head>
        <title>{`Henry Gomez | ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <nav data-theme={ checked ? theme.light : theme.dark } className={openSans.className}>
        <Navbar/>
      </nav>
      <main data-theme={ checked ? theme.dark : theme.light } className={openSans.className}>
        {children}
      </main>
      <footer>

      </footer>
    </>
  )
}